---

- name: Run plays
  hosts: web:tws 
 
  #web:tws 
  tasks:
    - name: Setup enviroment for specific host 
      tags: enviroment
      block:
        - include_vars:
            file: 'vars1.yaml' 
        - include_role:
            name: 'roles/enviroment.yml'

    - name: setup kvm-bridge for specific host 
      tags: bridge
      block:
        - include_vars:
            file: 'vars2.yaml'
        - include_role:
            name: 'roles/bridge.yml'

    - name: Setup Nextcloud for specific host 
      tags: nextcloud 
      block:
        - include_vars:
            file: 'vars2.yaml'
        - include_role:
            name: 'roles/nextcloud.yml'

