---

- name: Run plays
  hosts: web:tws 
 
  #web:tws 
  tasks:
    - name: Setup enviroment for specific host 
      tags: enviroment
      block:
        - include_vars:
            file: 'vars1.yaml' 
        - include_role:
            name: 'roles/setup.yaml'

    - name: Setup kvm-bridge for host 
      tags: bridge
      block:
        - include_vars:
            file: 'vars2.yaml'
        - include_role:
            name: 'roles/bridge.yaml'

    - name: Setup Nextcloud Server
      tags: nextcloud 
      block:
        - include_vars:
            file: 'vars3.yaml'
        - include_role:
            name: 'roles/nextcloud.yaml'

